// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: proto/photo_upload.proto

package photo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FaceAnalysis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emotion    string  `protobuf:"bytes,1,opt,name=emotion,proto3" json:"emotion,omitempty"`
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
}

func (x *FaceAnalysis) Reset() {
	*x = FaceAnalysis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_photo_upload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaceAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceAnalysis) ProtoMessage() {}

func (x *FaceAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photo_upload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceAnalysis.ProtoReflect.Descriptor instead.
func (*FaceAnalysis) Descriptor() ([]byte, []int) {
	return file_proto_photo_upload_proto_rawDescGZIP(), []int{0}
}

func (x *FaceAnalysis) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *FaceAnalysis) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type UploadedImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url          string          `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	FaceAnalysis []*FaceAnalysis `protobuf:"bytes,3,rep,name=face_analysis,json=faceAnalysis,proto3" json:"face_analysis,omitempty"`
	UploadTime   int64           `protobuf:"varint,4,opt,name=upload_time,json=uploadTime,proto3" json:"upload_time,omitempty"` // UploadTime alanını ekledik
}

func (x *UploadedImage) Reset() {
	*x = UploadedImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_photo_upload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadedImage) ProtoMessage() {}

func (x *UploadedImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photo_upload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadedImage.ProtoReflect.Descriptor instead.
func (*UploadedImage) Descriptor() ([]byte, []int) {
	return file_proto_photo_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadedImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadedImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadedImage) GetFaceAnalysis() []*FaceAnalysis {
	if x != nil {
		return x.FaceAnalysis
	}
	return nil
}

func (x *UploadedImage) GetUploadTime() int64 {
	if x != nil {
		return x.UploadTime
	}
	return 0
}

type GetImageFeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNumber int32 `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize   int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *GetImageFeedRequest) Reset() {
	*x = GetImageFeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_photo_upload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageFeedRequest) ProtoMessage() {}

func (x *GetImageFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photo_upload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageFeedRequest.ProtoReflect.Descriptor instead.
func (*GetImageFeedRequest) Descriptor() ([]byte, []int) {
	return file_proto_photo_upload_proto_rawDescGZIP(), []int{2}
}

func (x *GetImageFeedRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *GetImageFeedRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetImageFeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Images []*UploadedImage `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *GetImageFeedResponse) Reset() {
	*x = GetImageFeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_photo_upload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageFeedResponse) ProtoMessage() {}

func (x *GetImageFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_photo_upload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageFeedResponse.ProtoReflect.Descriptor instead.
func (*GetImageFeedResponse) Descriptor() ([]byte, []int) {
	return file_proto_photo_upload_proto_rawDescGZIP(), []int{3}
}

func (x *GetImageFeedResponse) GetImages() []*UploadedImage {
	if x != nil {
		return x.Images
	}
	return nil
}

var File_proto_photo_upload_proto protoreflect.FileDescriptor

var file_proto_photo_upload_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x75, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x22, 0x48, 0x0a, 0x0c, 0x46, 0x61, 0x63, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x0d,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x38, 0x0a, 0x0d, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x46,
	0x61, 0x63, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x0c, 0x66, 0x61, 0x63,
	0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x53, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x44, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x32, 0x91, 0x02, 0x0a, 0x0c, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x3c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x14, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x65, 0x65, 0x64, 0x12,
	0x1a, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x2e,
	0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x6d, 0x79, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_photo_upload_proto_rawDescOnce sync.Once
	file_proto_photo_upload_proto_rawDescData = file_proto_photo_upload_proto_rawDesc
)

func file_proto_photo_upload_proto_rawDescGZIP() []byte {
	file_proto_photo_upload_proto_rawDescOnce.Do(func() {
		file_proto_photo_upload_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_photo_upload_proto_rawDescData)
	})
	return file_proto_photo_upload_proto_rawDescData
}

var file_proto_photo_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_photo_upload_proto_goTypes = []interface{}{
	(*FaceAnalysis)(nil),         // 0: photo.FaceAnalysis
	(*UploadedImage)(nil),        // 1: photo.UploadedImage
	(*GetImageFeedRequest)(nil),  // 2: photo.GetImageFeedRequest
	(*GetImageFeedResponse)(nil), // 3: photo.GetImageFeedResponse
}
var file_proto_photo_upload_proto_depIdxs = []int32{
	0, // 0: photo.UploadedImage.face_analysis:type_name -> photo.FaceAnalysis
	1, // 1: photo.GetImageFeedResponse.images:type_name -> photo.UploadedImage
	1, // 2: photo.PhotoService.UploadImage:input_type -> photo.UploadedImage
	1, // 3: photo.PhotoService.GetImageDetail:input_type -> photo.UploadedImage
	2, // 4: photo.PhotoService.GetImageFeed:input_type -> photo.GetImageFeedRequest
	1, // 5: photo.PhotoService.UpdateImageDetail:input_type -> photo.UploadedImage
	1, // 6: photo.PhotoService.UploadImage:output_type -> photo.UploadedImage
	1, // 7: photo.PhotoService.GetImageDetail:output_type -> photo.UploadedImage
	3, // 8: photo.PhotoService.GetImageFeed:output_type -> photo.GetImageFeedResponse
	1, // 9: photo.PhotoService.UpdateImageDetail:output_type -> photo.UploadedImage
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_photo_upload_proto_init() }
func file_proto_photo_upload_proto_init() {
	if File_proto_photo_upload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_photo_upload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaceAnalysis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_photo_upload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadedImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_photo_upload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImageFeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_photo_upload_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImageFeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_photo_upload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_photo_upload_proto_goTypes,
		DependencyIndexes: file_proto_photo_upload_proto_depIdxs,
		MessageInfos:      file_proto_photo_upload_proto_msgTypes,
	}.Build()
	File_proto_photo_upload_proto = out.File
	file_proto_photo_upload_proto_rawDesc = nil
	file_proto_photo_upload_proto_goTypes = nil
	file_proto_photo_upload_proto_depIdxs = nil
}
